# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 18:18
from __future__ import unicode_literals

import demo.models
from django.db import migrations, models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_auto_20160902_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpagecarouselitem',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='eventpagecarouselitem',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='homepagecarouselitem',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='standardpagecarouselitem',
            name='caption',
        ),
        migrations.AddField(
            model_name='blogpagecarouselitem',
            name='descrizione',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AddField(
            model_name='blogpagecarouselitem',
            name='stile_slide',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AddField(
            model_name='blogpagecarouselitem',
            name='titolo',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AddField(
            model_name='eventpagecarouselitem',
            name='descrizione',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AddField(
            model_name='eventpagecarouselitem',
            name='stile_slide',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AddField(
            model_name='eventpagecarouselitem',
            name='titolo',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AddField(
            model_name='homepagecarouselitem',
            name='descrizione',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AddField(
            model_name='homepagecarouselitem',
            name='stile_slide',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AddField(
            model_name='homepagecarouselitem',
            name='titolo',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AddField(
            model_name='standardpagecarouselitem',
            name='descrizione',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AddField(
            model_name='standardpagecarouselitem',
            name='stile_slide',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AddField(
            model_name='standardpagecarouselitem',
            name='titolo',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('h2', wagtail.wagtailcore.blocks.CharBlock(classname='title', icon='title')), ('h3', wagtail.wagtailcore.blocks.CharBlock(classname='title', icon='title')), ('h4', wagtail.wagtailcore.blocks.CharBlock(classname='title', icon='title')), ('h5', wagtail.wagtailcore.blocks.CharBlock(classname='title', icon='title')), ('h6', wagtail.wagtailcore.blocks.CharBlock(classname='title', icon='title')), ('intro', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow')), ('aligned_image', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('caption', wagtail.wagtailcore.blocks.RichTextBlock()), ('alignment', demo.models.ImageFormatChoiceBlock())), icon='image', label='Aligned image')), ('pullquote', wagtail.wagtailcore.blocks.StructBlock((('quote', wagtail.wagtailcore.blocks.TextBlock('quote title')), ('attribution', wagtail.wagtailcore.blocks.CharBlock())))), ('aligned_html', wagtail.wagtailcore.blocks.StructBlock((('html', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('alignment', demo.models.HTMLAlignmentChoiceBlock())), icon='code', label='Raw HTML')), ('document', wagtail.wagtaildocs.blocks.DocumentChooserBlock(icon='doc-full-inverse')))),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='address_1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Indirizzo'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='address_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Indirizzo Alt'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name='Citta'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='country',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nazione'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='post_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='CAP'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='audience',
            field=models.CharField(choices=[('libero', 'Libero'), ('pagamento', 'Pagamento')], max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('h2', wagtail.wagtailcore.blocks.CharBlock(classname='title', icon='title')), ('h3', wagtail.wagtailcore.blocks.CharBlock(classname='title', icon='title')), ('h4', wagtail.wagtailcore.blocks.CharBlock(classname='title', icon='title')), ('h5', wagtail.wagtailcore.blocks.CharBlock(classname='title', icon='title')), ('h6', wagtail.wagtailcore.blocks.CharBlock(classname='title', icon='title')), ('intro', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow')), ('aligned_image', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('caption', wagtail.wagtailcore.blocks.RichTextBlock()), ('alignment', demo.models.ImageFormatChoiceBlock())), icon='image', label='Aligned image')), ('pullquote', wagtail.wagtailcore.blocks.StructBlock((('quote', wagtail.wagtailcore.blocks.TextBlock('quote title')), ('attribution', wagtail.wagtailcore.blocks.CharBlock())))), ('aligned_html', wagtail.wagtailcore.blocks.StructBlock((('html', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('alignment', demo.models.HTMLAlignmentChoiceBlock())), icon='code', label='Raw HTML')), ('document', wagtail.wagtaildocs.blocks.DocumentChooserBlock(icon='doc-full-inverse')))),
        ),
        migrations.AlterField(
            model_name='personpage',
            name='address_1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Indirizzo'),
        ),
        migrations.AlterField(
            model_name='personpage',
            name='address_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Indirizzo Alt'),
        ),
        migrations.AlterField(
            model_name='personpage',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name='Citta'),
        ),
        migrations.AlterField(
            model_name='personpage',
            name='country',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nazione'),
        ),
        migrations.AlterField(
            model_name='personpage',
            name='post_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='CAP'),
        ),
        migrations.AlterField(
            model_name='personpage',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefono'),
        ),
    ]
