# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0010_auto_20161006_1943'),
    ]

    operations = [
    ]
