# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailimages', '0015_fill_filter_spec_field'),
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtaildocs', '0007_merge'),
        ('wagtailcore', '0030_index_on_pagerevision_created_at'),
        ('demo', '0011_auto_20161006_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPageGalleria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('link_external', models.URLField(blank=True, verbose_name='External link')),
                ('titolo', models.CharField(blank=True, max_length=55)),
                ('descrizione', models.CharField(blank=True, max_length=155)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('link_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.Document')),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlogPageLinkEsterno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('link_external', models.URLField(blank=True, verbose_name='External link')),
                ('title', models.CharField(help_text='Link title', max_length=255)),
                ('link_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.Document')),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='blogindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='blogindexpagerelatedlink',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='blogindexpagerelatedlink',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='blogindexpagerelatedlink',
            name='page',
        ),
        migrations.AlterModelOptions(
            name='blogpage',
            options={'verbose_name': 'Pagina Progetto'},
        ),
        migrations.RenameField(
            model_name='blogpage',
            old_name='body',
            new_name='campi_dinamici',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='intro',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Data Pubblicazione'),
        ),
        migrations.DeleteModel(
            name='BlogIndexPage',
        ),
        migrations.DeleteModel(
            name='BlogIndexPageRelatedLink',
        ),
        migrations.AddField(
            model_name='blogpagelinkesterno',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_esterno', to='demo.BlogPage'),
        ),
        migrations.AddField(
            model_name='blogpagegalleria',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleria_blog', to='demo.BlogPage'),
        ),
    ]
