# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0007_merge'),
        ('wagtailcore', '0030_index_on_pagerevision_created_at'),
        ('wagtailimages', '0015_fill_filter_spec_field'),
        ('demo', '0013_blogindexpage_blogindexpagelinkesterno_blogindexpagerelatedlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonPageLinkEsterno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('link_external', models.URLField(blank=True, verbose_name='External link')),
                ('title', models.CharField(help_text='Link title', max_length=255)),
                ('link_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.Document')),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
        migrations.AlterModelOptions(
            name='contactpage',
            options={'verbose_name': 'Pagina Contatti'},
        ),
        migrations.AlterModelOptions(
            name='personpage',
            options={'verbose_name': 'Pagina Persona'},
        ),
        migrations.AddField(
            model_name='personpage',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='personpage',
            name='biography',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='Curriculum'),
        ),
        migrations.AlterField(
            model_name='personpage',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='personpage',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Cognome'),
        ),
        migrations.AddField(
            model_name='personpagelinkesterno',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_esterno', to='demo.PersonPage'),
        ),
    ]
