# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0030_index_on_pagerevision_created_at'),
        ('demo', '0016_eventpage_eventpagelinkesterno_eventpagerelatedlink_eventpagespeaker'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='Titolo Parallasse')),
                ('secondo_messaggio', wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='Secondo Titolo Parallasse')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
