# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 06:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0030_index_on_pagerevision_created_at'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('demo', '0017_legacypage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='eventindexpagelinkesterno',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='eventindexpagelinkesterno',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='eventindexpagelinkesterno',
            name='page',
        ),
        migrations.RemoveField(
            model_name='eventindexpagerelatedlink',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='eventindexpagerelatedlink',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='eventindexpagerelatedlink',
            name='page',
        ),
        migrations.DeleteModel(
            name='EventIndexPage',
        ),
        migrations.DeleteModel(
            name='EventIndexPageLinkEsterno',
        ),
        migrations.DeleteModel(
            name='EventIndexPageRelatedLink',
        ),
    ]
