# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0020_auto_20161007_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpagecarousel',
            name='descrizione',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AlterField(
            model_name='aboutpagecarousel',
            name='titolo',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AlterField(
            model_name='blogpagecarouselitem',
            name='descrizione',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AlterField(
            model_name='blogpagecarouselitem',
            name='titolo',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AlterField(
            model_name='homepagecarouselitem',
            name='descrizione',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AlterField(
            model_name='homepagecarouselitem',
            name='titolo',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AlterField(
            model_name='standardpagecarouselitem',
            name='descrizione',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AlterField(
            model_name='standardpagecarouselitem',
            name='titolo',
            field=models.CharField(blank=True, max_length=55),
        ),
    ]
