# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 13:41
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0021_auto_20161007_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpagecarousel',
            name='descrizione',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='Descrizione Carousel'),
        ),
        migrations.AlterField(
            model_name='aboutpagecarousel',
            name='titolo',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='Titolo Carousel'),
        ),
        migrations.AlterField(
            model_name='blogpagecarouselitem',
            name='descrizione',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='Descrizione Carousel'),
        ),
        migrations.AlterField(
            model_name='blogpagecarouselitem',
            name='titolo',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='Titolo Carousel'),
        ),
        migrations.AlterField(
            model_name='homepagecarouselitem',
            name='descrizione',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='Descrizione Carousel'),
        ),
        migrations.AlterField(
            model_name='homepagecarouselitem',
            name='titolo',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='Titolo Carousel'),
        ),
        migrations.AlterField(
            model_name='standardpagecarouselitem',
            name='descrizione',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='Descrizione Carousel'),
        ),
        migrations.AlterField(
            model_name='standardpagecarouselitem',
            name='titolo',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='Titolo Carousel'),
        ),
    ]
